/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  useSpring,
  animated,
  useSpringRef,
  useChain,
  AnimationResult,
} from "@react-spring/three"
import { useEffect, useRef, useState } from "react"
import { Gunslinger, GunslingerAnimation } from "../models/Gunslinger"

export enum Target {
  Default,
  A,
  B,
  C,
}

export const Character: React.FC<{ target: Target }> = ({ target }) => {
  const [animation, setAnimation] = useState(GunslingerAnimation.Idle)
  const [deltaRT, setDeltaRY] = useState(0)

  useEffect(() => {
    if (target === Target.Default) {
      return
    }
    start()
  }, [target])

  const start = () => {
    setAnimation(GunslingerAnimation.Stop)
    setDeltaRY(Math.PI / 4.0)
  }

  const speed = 0.2

  const pzRef = useSpringRef()
  const { ry } = useSpring({
    from: { ry: 0 },
    to: { ry: deltaRT },
    config: { duration: deltaRT * speed * 1000 },
    ref: pzRef,
  })

  useChain([pzRef])

  return (
    <animated.group rotation-y={ry}>
      <Gunslinger animation={animation} />
    </animated.group>
  )
}
