/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"
import { CharacterState, useCharacterState } from "../hooks/use-character-state"

type GLTFResult = GLTF & {
  nodes: {
    Mesh001: THREE.SkinnedMesh
    Mesh001_1: THREE.SkinnedMesh
    Mesh001_2: THREE.SkinnedMesh
    Mesh001_3: THREE.SkinnedMesh
    Mesh006: THREE.SkinnedMesh
    Mesh006_1: THREE.SkinnedMesh
    brow_016: THREE.SkinnedMesh
    Mesh009: THREE.SkinnedMesh
    Mesh009_1: THREE.SkinnedMesh
    Mesh007: THREE.SkinnedMesh
    Mesh007_1: THREE.SkinnedMesh
    Mesh010: THREE.SkinnedMesh
    Mesh010_1: THREE.SkinnedMesh
    Mesh012: THREE.SkinnedMesh
    Mesh012_1: THREE.SkinnedMesh
    Mesh012_2: THREE.SkinnedMesh
    Mesh002: THREE.SkinnedMesh
    Mesh002_1: THREE.SkinnedMesh
    Mesh011: THREE.SkinnedMesh
    Mesh011_1: THREE.SkinnedMesh
    Mesh004: THREE.SkinnedMesh
    Mesh004_1: THREE.SkinnedMesh
    Mesh013: THREE.SkinnedMesh
    Mesh013_1: THREE.SkinnedMesh
    Mesh013_2: THREE.SkinnedMesh
    Mesh013_3: THREE.SkinnedMesh
    Mesh005: THREE.SkinnedMesh
    Mesh005_1: THREE.SkinnedMesh
    Mesh005_2: THREE.SkinnedMesh
    tool_002: THREE.SkinnedMesh
    Mesh: THREE.SkinnedMesh
    Mesh_1: THREE.SkinnedMesh
    Mesh_2: THREE.SkinnedMesh
    mixamorig_Hips: THREE.Bone
  }
  materials: {
    Worker_black: THREE.MeshStandardMaterial
    Worker_leather: THREE.MeshStandardMaterial
    Worker_metal: THREE.MeshStandardMaterial
    Worker_neon: THREE.MeshStandardMaterial
    Worker_skin: THREE.MeshStandardMaterial
    Worker_beard: THREE.MeshStandardMaterial
    Doc_red_cross: THREE.MeshStandardMaterial
    ["skin.047"]: THREE.MeshStandardMaterial
    ["black.005"]: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    ["skin.046"]: THREE.MeshStandardMaterial
    ["skin.044"]: THREE.MeshStandardMaterial
    Worker_orange: THREE.MeshStandardMaterial
  }
}

export const CompoWorker: React.FC<{
  state: CharacterState
}> = (props) => {
  const group = useRef<THREE.Group>(null)

  const { nodes, materials, animations } = useGLTF(
    "/gltf/m_compo_worker.glb"
  ) as GLTFResult

  useCharacterState(props.state, animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="dock_worker_002"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig_Hips} />
          <group name="belts_pockets_002">
            <skinnedMesh
              name="Mesh001"
              geometry={nodes.Mesh001.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh001.skeleton}
            />
            <skinnedMesh
              name="Mesh001_1"
              geometry={nodes.Mesh001_1.geometry}
              material={materials.Worker_leather}
              skeleton={nodes.Mesh001_1.skeleton}
            />
            <skinnedMesh
              name="Mesh001_2"
              geometry={nodes.Mesh001_2.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh001_2.skeleton}
            />
            <skinnedMesh
              name="Mesh001_3"
              geometry={nodes.Mesh001_3.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh001_3.skeleton}
            />
          </group>
          <group name="body_016">
            <skinnedMesh
              name="Mesh006"
              geometry={nodes.Mesh006.geometry}
              material={materials.Worker_skin}
              skeleton={nodes.Mesh006.skeleton}
            />
            <skinnedMesh
              name="Mesh006_1"
              geometry={nodes.Mesh006_1.geometry}
              material={materials.Worker_beard}
              skeleton={nodes.Mesh006_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="brow_016"
            geometry={nodes.brow_016.geometry}
            material={materials.Worker_beard}
            skeleton={nodes.brow_016.skeleton}
          />
          <group name="cigarette_002">
            <skinnedMesh
              name="Mesh009"
              geometry={nodes.Mesh009.geometry}
              material={materials.Doc_red_cross}
              skeleton={nodes.Mesh009.skeleton}
            />
            <skinnedMesh
              name="Mesh009_1"
              geometry={nodes.Mesh009_1.geometry}
              material={materials["skin.047"]}
              skeleton={nodes.Mesh009_1.skeleton}
            />
          </group>
          <group name="eye_012">
            <skinnedMesh
              name="Mesh007"
              geometry={nodes.Mesh007.geometry}
              material={materials["black.005"]}
              skeleton={nodes.Mesh007.skeleton}
            />
            <skinnedMesh
              name="Mesh007_1"
              geometry={nodes.Mesh007_1.geometry}
              material={materials.White}
              skeleton={nodes.Mesh007_1.skeleton}
            />
          </group>
          <group name="eye_patch_002">
            <skinnedMesh
              name="Mesh010"
              geometry={nodes.Mesh010.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh010.skeleton}
            />
            <skinnedMesh
              name="Mesh010_1"
              geometry={nodes.Mesh010_1.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh010_1.skeleton}
            />
          </group>
          <group name="gloves_007">
            <skinnedMesh
              name="Mesh012"
              geometry={nodes.Mesh012.geometry}
              material={materials.Worker_leather}
              skeleton={nodes.Mesh012.skeleton}
            />
            <skinnedMesh
              name="Mesh012_1"
              geometry={nodes.Mesh012_1.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh012_1.skeleton}
            />
            <skinnedMesh
              name="Mesh012_2"
              geometry={nodes.Mesh012_2.geometry}
              material={materials.Worker_skin}
              skeleton={nodes.Mesh012_2.skeleton}
            />
          </group>
          <group name="hammer_002">
            <skinnedMesh
              name="Mesh002"
              geometry={nodes.Mesh002.geometry}
              material={materials["skin.046"]}
              skeleton={nodes.Mesh002.skeleton}
            />
            <skinnedMesh
              name="Mesh002_1"
              geometry={nodes.Mesh002_1.geometry}
              material={materials["skin.044"]}
              skeleton={nodes.Mesh002_1.skeleton}
            />
          </group>
          <group name="hat_007">
            <skinnedMesh
              name="Mesh011"
              geometry={nodes.Mesh011.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh011.skeleton}
            />
            <skinnedMesh
              name="Mesh011_1"
              geometry={nodes.Mesh011_1.geometry}
              material={materials.Worker_orange}
              skeleton={nodes.Mesh011_1.skeleton}
            />
          </group>
          <group name="screwdriver_002">
            <skinnedMesh
              name="Mesh004"
              geometry={nodes.Mesh004.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh004.skeleton}
            />
            <skinnedMesh
              name="Mesh004_1"
              geometry={nodes.Mesh004_1.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh004_1.skeleton}
            />
          </group>
          <group name="shoes_010">
            <skinnedMesh
              name="Mesh013"
              geometry={nodes.Mesh013.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh013.skeleton}
            />
            <skinnedMesh
              name="Mesh013_1"
              geometry={nodes.Mesh013_1.geometry}
              material={materials.Worker_leather}
              skeleton={nodes.Mesh013_1.skeleton}
            />
            <skinnedMesh
              name="Mesh013_2"
              geometry={nodes.Mesh013_2.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh013_2.skeleton}
            />
            <skinnedMesh
              name="Mesh013_3"
              geometry={nodes.Mesh013_3.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh013_3.skeleton}
            />
          </group>
          <group name="suit_002">
            <skinnedMesh
              name="Mesh005"
              geometry={nodes.Mesh005.geometry}
              material={materials.Worker_orange}
              skeleton={nodes.Mesh005.skeleton}
            />
            <skinnedMesh
              name="Mesh005_1"
              geometry={nodes.Mesh005_1.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh005_1.skeleton}
            />
            <skinnedMesh
              name="Mesh005_2"
              geometry={nodes.Mesh005_2.geometry}
              material={materials["skin.047"]}
              skeleton={nodes.Mesh005_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="tool_002"
            geometry={nodes.tool_002.geometry}
            material={materials.Worker_metal}
            skeleton={nodes.tool_002.skeleton}
          />
          <group name="wench_002">
            <skinnedMesh
              name="Mesh"
              geometry={nodes.Mesh.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh.skeleton}
            />
            <skinnedMesh
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh_1.skeleton}
            />
            <skinnedMesh
              name="Mesh_2"
              geometry={nodes.Mesh_2.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/gltf/m_compo_worker.glb")
