/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"
import { useCharacterAnimations } from "../../hooks/use-character-animations"
import { CharacterSkin } from "./CharacterSkin"

type GLTFResult = GLTF & {
  nodes: {
    Mesh205: THREE.SkinnedMesh
    Mesh205_1: THREE.SkinnedMesh
    Mesh205_2: THREE.SkinnedMesh
    Mesh205_3: THREE.SkinnedMesh
    Mesh210: THREE.SkinnedMesh
    Mesh210_1: THREE.SkinnedMesh
    brow016: THREE.SkinnedMesh
    Mesh213: THREE.SkinnedMesh
    Mesh213_1: THREE.SkinnedMesh
    Mesh211: THREE.SkinnedMesh
    Mesh211_1: THREE.SkinnedMesh
    Mesh214: THREE.SkinnedMesh
    Mesh214_1: THREE.SkinnedMesh
    Mesh216: THREE.SkinnedMesh
    Mesh216_1: THREE.SkinnedMesh
    Mesh216_2: THREE.SkinnedMesh
    Mesh206: THREE.SkinnedMesh
    Mesh206_1: THREE.SkinnedMesh
    Mesh215: THREE.SkinnedMesh
    Mesh215_1: THREE.SkinnedMesh
    Mesh208: THREE.SkinnedMesh
    Mesh208_1: THREE.SkinnedMesh
    Mesh217: THREE.SkinnedMesh
    Mesh217_1: THREE.SkinnedMesh
    Mesh217_2: THREE.SkinnedMesh
    Mesh217_3: THREE.SkinnedMesh
    Mesh209: THREE.SkinnedMesh
    Mesh209_1: THREE.SkinnedMesh
    Mesh209_2: THREE.SkinnedMesh
    tool002: THREE.SkinnedMesh
    Mesh204: THREE.SkinnedMesh
    Mesh204_1: THREE.SkinnedMesh
    Mesh204_2: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Worker_black: THREE.MeshStandardMaterial
    Worker_metal: THREE.MeshStandardMaterial
    Worker_neon: THREE.MeshStandardMaterial
    Worker_leather: THREE.MeshStandardMaterial
    Worker_beard: THREE.MeshStandardMaterial
    Worker_skin: THREE.MeshStandardMaterial
    ["skin.047"]: THREE.MeshStandardMaterial
    Doc_red_cross: THREE.MeshStandardMaterial
    ["black.005"]: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    ["skin.046"]: THREE.MeshStandardMaterial
    ["skin.044"]: THREE.MeshStandardMaterial
    Worker_orange: THREE.MeshStandardMaterial
  }
}

export const CompoWorker: CharacterSkin = (props) => {
  const group = useRef<THREE.Group>(null)

  const { nodes, materials, animations } = useGLTF(
    "/gltf/m_compo_worker.glb"
  ) as GLTFResult

  useCharacterAnimations(props.state, animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="dock_worker002"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="belts_pockets002">
            <skinnedMesh
              name="Mesh205"
              geometry={nodes.Mesh205.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh205.skeleton}
            />
            <skinnedMesh
              name="Mesh205_1"
              geometry={nodes.Mesh205_1.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh205_1.skeleton}
            />
            <skinnedMesh
              name="Mesh205_2"
              geometry={nodes.Mesh205_2.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh205_2.skeleton}
            />
            <skinnedMesh
              name="Mesh205_3"
              geometry={nodes.Mesh205_3.geometry}
              material={materials.Worker_leather}
              skeleton={nodes.Mesh205_3.skeleton}
            />
          </group>
          <group name="body016">
            <skinnedMesh
              name="Mesh210"
              geometry={nodes.Mesh210.geometry}
              material={materials.Worker_beard}
              skeleton={nodes.Mesh210.skeleton}
            />
            <skinnedMesh
              name="Mesh210_1"
              geometry={nodes.Mesh210_1.geometry}
              material={materials.Worker_skin}
              skeleton={nodes.Mesh210_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="brow016"
            geometry={nodes.brow016.geometry}
            material={materials.Worker_beard}
            skeleton={nodes.brow016.skeleton}
          />
          <group name="cigarette002">
            <skinnedMesh
              name="Mesh213"
              geometry={nodes.Mesh213.geometry}
              material={materials["skin.047"]}
              skeleton={nodes.Mesh213.skeleton}
            />
            <skinnedMesh
              name="Mesh213_1"
              geometry={nodes.Mesh213_1.geometry}
              material={materials.Doc_red_cross}
              skeleton={nodes.Mesh213_1.skeleton}
            />
          </group>
          <group name="eye012">
            <skinnedMesh
              name="Mesh211"
              geometry={nodes.Mesh211.geometry}
              material={materials["black.005"]}
              skeleton={nodes.Mesh211.skeleton}
            />
            <skinnedMesh
              name="Mesh211_1"
              geometry={nodes.Mesh211_1.geometry}
              material={materials.White}
              skeleton={nodes.Mesh211_1.skeleton}
            />
          </group>
          <group name="eye_patch002">
            <skinnedMesh
              name="Mesh214"
              geometry={nodes.Mesh214.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh214.skeleton}
            />
            <skinnedMesh
              name="Mesh214_1"
              geometry={nodes.Mesh214_1.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh214_1.skeleton}
            />
          </group>
          <group name="gloves007">
            <skinnedMesh
              name="Mesh216"
              geometry={nodes.Mesh216.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh216.skeleton}
            />
            <skinnedMesh
              name="Mesh216_1"
              geometry={nodes.Mesh216_1.geometry}
              material={materials.Worker_leather}
              skeleton={nodes.Mesh216_1.skeleton}
            />
            <skinnedMesh
              name="Mesh216_2"
              geometry={nodes.Mesh216_2.geometry}
              material={materials.Worker_skin}
              skeleton={nodes.Mesh216_2.skeleton}
            />
          </group>
          <group name="hammer002">
            <skinnedMesh
              name="Mesh206"
              geometry={nodes.Mesh206.geometry}
              material={materials["skin.046"]}
              skeleton={nodes.Mesh206.skeleton}
            />
            <skinnedMesh
              name="Mesh206_1"
              geometry={nodes.Mesh206_1.geometry}
              material={materials["skin.044"]}
              skeleton={nodes.Mesh206_1.skeleton}
            />
          </group>
          <group name="hat007">
            <skinnedMesh
              name="Mesh215"
              geometry={nodes.Mesh215.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh215.skeleton}
            />
            <skinnedMesh
              name="Mesh215_1"
              geometry={nodes.Mesh215_1.geometry}
              material={materials.Worker_orange}
              skeleton={nodes.Mesh215_1.skeleton}
            />
          </group>
          <group name="screwdriver002">
            <skinnedMesh
              name="Mesh208"
              geometry={nodes.Mesh208.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh208.skeleton}
            />
            <skinnedMesh
              name="Mesh208_1"
              geometry={nodes.Mesh208_1.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh208_1.skeleton}
            />
          </group>
          <group name="shoes010">
            <skinnedMesh
              name="Mesh217"
              geometry={nodes.Mesh217.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh217.skeleton}
            />
            <skinnedMesh
              name="Mesh217_1"
              geometry={nodes.Mesh217_1.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh217_1.skeleton}
            />
            <skinnedMesh
              name="Mesh217_2"
              geometry={nodes.Mesh217_2.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh217_2.skeleton}
            />
            <skinnedMesh
              name="Mesh217_3"
              geometry={nodes.Mesh217_3.geometry}
              material={materials.Worker_leather}
              skeleton={nodes.Mesh217_3.skeleton}
            />
          </group>
          <group name="suit002">
            <skinnedMesh
              name="Mesh209"
              geometry={nodes.Mesh209.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh209.skeleton}
            />
            <skinnedMesh
              name="Mesh209_1"
              geometry={nodes.Mesh209_1.geometry}
              material={materials.Worker_orange}
              skeleton={nodes.Mesh209_1.skeleton}
            />
            <skinnedMesh
              name="Mesh209_2"
              geometry={nodes.Mesh209_2.geometry}
              material={materials["skin.047"]}
              skeleton={nodes.Mesh209_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="tool002"
            geometry={nodes.tool002.geometry}
            material={materials.Worker_metal}
            skeleton={nodes.tool002.skeleton}
          />
          <group name="wench002">
            <skinnedMesh
              name="Mesh204"
              geometry={nodes.Mesh204.geometry}
              material={materials.Worker_black}
              skeleton={nodes.Mesh204.skeleton}
            />
            <skinnedMesh
              name="Mesh204_1"
              geometry={nodes.Mesh204_1.geometry}
              material={materials.Worker_metal}
              skeleton={nodes.Mesh204_1.skeleton}
            />
            <skinnedMesh
              name="Mesh204_2"
              geometry={nodes.Mesh204_2.geometry}
              material={materials.Worker_neon}
              skeleton={nodes.Mesh204_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/gltf/m_compo_worker.glb")
