/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"
import { useCharacterAnimations } from "../../hooks/use-character-animations"
import { CharacterSkin } from "./CharacterSkin"

type GLTFResult = GLTF & {
  nodes: {
    Mesh005: THREE.SkinnedMesh
    Mesh005_1: THREE.SkinnedMesh
    Mesh005_2: THREE.SkinnedMesh
    Mesh010: THREE.SkinnedMesh
    Mesh010_1: THREE.SkinnedMesh
    Mesh010_2: THREE.SkinnedMesh
    brow_014: THREE.SkinnedMesh
    Mesh011: THREE.SkinnedMesh
    Mesh011_1: THREE.SkinnedMesh
    fire: THREE.SkinnedMesh
    fire_2: THREE.SkinnedMesh
    gloves_006: THREE.SkinnedMesh
    hat_006: THREE.SkinnedMesh
    Mesh001: THREE.SkinnedMesh
    Mesh001_1: THREE.SkinnedMesh
    Mesh: THREE.SkinnedMesh
    Mesh_1: THREE.SkinnedMesh
    Mesh_2: THREE.SkinnedMesh
    Mesh_3: THREE.SkinnedMesh
    Mesh014: THREE.SkinnedMesh
    Mesh014_1: THREE.SkinnedMesh
    mustache_002: THREE.SkinnedMesh
    neck_002: THREE.SkinnedMesh
    protection_002: THREE.SkinnedMesh
    Mesh009: THREE.SkinnedMesh
    Mesh009_1: THREE.SkinnedMesh
    Mesh009_2: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    ["guns_metal.001"]: THREE.MeshStandardMaterial
    ["guns_neon.001"]: THREE.MeshStandardMaterial
    ["guns_leather.001"]: THREE.MeshStandardMaterial
    guns_black: THREE.MeshStandardMaterial
    guns_skin: THREE.MeshStandardMaterial
    guns_hair_mustache: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    guns_neon: THREE.MeshStandardMaterial
    guns_brown: THREE.MeshStandardMaterial
    guns_metal: THREE.MeshStandardMaterial
    guns_leather: THREE.MeshStandardMaterial
    guns_black_2: THREE.MeshStandardMaterial
    ["pasky.022"]: THREE.MeshStandardMaterial
  }
}

export const Gunslinger: CharacterSkin = (props) => {
  const group = useRef<THREE.Group>(null)

  const { nodes, materials, animations } = useGLTF(
    "/gltf/m_gunslinger.glb"
  ) as GLTFResult

  useCharacterAnimations(props.state, animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="gunslinger" rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="belts_buckles_002">
            <skinnedMesh
              name="Mesh005"
              geometry={nodes.Mesh005.geometry}
              material={materials["guns_metal.001"]}
              skeleton={nodes.Mesh005.skeleton}
            />
            <skinnedMesh
              name="Mesh005_1"
              geometry={nodes.Mesh005_1.geometry}
              material={materials["guns_neon.001"]}
              skeleton={nodes.Mesh005_1.skeleton}
            />
            <skinnedMesh
              name="Mesh005_2"
              geometry={nodes.Mesh005_2.geometry}
              material={materials["guns_leather.001"]}
              skeleton={nodes.Mesh005_2.skeleton}
            />
          </group>
          <group name="body_014">
            <skinnedMesh
              name="Mesh010"
              geometry={nodes.Mesh010.geometry}
              material={materials.guns_black}
              skeleton={nodes.Mesh010.skeleton}
            />
            <skinnedMesh
              name="Mesh010_1"
              geometry={nodes.Mesh010_1.geometry}
              material={materials.guns_skin}
              skeleton={nodes.Mesh010_1.skeleton}
            />
            <skinnedMesh
              name="Mesh010_2"
              geometry={nodes.Mesh010_2.geometry}
              material={materials.guns_hair_mustache}
              skeleton={nodes.Mesh010_2.skeleton}
            />
            <group name="eyes_002" position={[0, 2.13, -81.73]} />
          </group>
          <skinnedMesh
            name="brow_014"
            geometry={nodes.brow_014.geometry}
            material={materials.guns_hair_mustache}
            skeleton={nodes.brow_014.skeleton}
          />
          <group name="Cube_079">
            <skinnedMesh
              name="Mesh011"
              geometry={nodes.Mesh011.geometry}
              material={materials.black}
              skeleton={nodes.Mesh011.skeleton}
            />
            <skinnedMesh
              name="Mesh011_1"
              geometry={nodes.Mesh011_1.geometry}
              material={materials.WHITE}
              skeleton={nodes.Mesh011_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="fire"
            geometry={nodes.fire.geometry}
            material={materials.guns_neon}
            skeleton={nodes.fire.skeleton}
          />
          <skinnedMesh
            name="fire_2"
            geometry={nodes.fire_2.geometry}
            material={materials.guns_neon}
            skeleton={nodes.fire_2.skeleton}
          />
          <skinnedMesh
            name="gloves_006"
            geometry={nodes.gloves_006.geometry}
            material={materials.guns_brown}
            skeleton={nodes.gloves_006.skeleton}
          />
          <skinnedMesh
            name="hat_006"
            geometry={nodes.hat_006.geometry}
            material={materials.guns_brown}
            skeleton={nodes.hat_006.skeleton}
          />
          <group name="jet">
            <skinnedMesh
              name="Mesh001"
              geometry={nodes.Mesh001.geometry}
              material={materials.guns_metal}
              skeleton={nodes.Mesh001.skeleton}
            />
            <skinnedMesh
              name="Mesh001_1"
              geometry={nodes.Mesh001_1.geometry}
              material={materials.guns_black}
              skeleton={nodes.Mesh001_1.skeleton}
            />
          </group>
          <group name="jetpack">
            <skinnedMesh
              name="Mesh"
              geometry={nodes.Mesh.geometry}
              material={materials.guns_metal}
              skeleton={nodes.Mesh.skeleton}
            />
            <skinnedMesh
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={materials.guns_black}
              skeleton={nodes.Mesh_1.skeleton}
            />
            <skinnedMesh
              name="Mesh_2"
              geometry={nodes.Mesh_2.geometry}
              material={materials.guns_leather}
              skeleton={nodes.Mesh_2.skeleton}
            />
            <skinnedMesh
              name="Mesh_3"
              geometry={nodes.Mesh_3.geometry}
              material={materials.guns_neon}
              skeleton={nodes.Mesh_3.skeleton}
            />
          </group>
          <group name="mask_B_001">
            <skinnedMesh
              name="Mesh014"
              geometry={nodes.Mesh014.geometry}
              material={materials["guns_neon.001"]}
              skeleton={nodes.Mesh014.skeleton}
            />
            <skinnedMesh
              name="Mesh014_1"
              geometry={nodes.Mesh014_1.geometry}
              material={materials.guns_black_2}
              skeleton={nodes.Mesh014_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="mustache_002"
            geometry={nodes.mustache_002.geometry}
            material={materials.guns_hair_mustache}
            skeleton={nodes.mustache_002.skeleton}
          />
          <skinnedMesh
            name="neck_002"
            geometry={nodes.neck_002.geometry}
            material={materials["pasky.022"]}
            skeleton={nodes.neck_002.skeleton}
          />
          <skinnedMesh
            name="protection_002"
            geometry={nodes.protection_002.geometry}
            material={materials["guns_metal.001"]}
            skeleton={nodes.protection_002.skeleton}
          />
          <group name="shoes_009">
            <skinnedMesh
              name="Mesh009"
              geometry={nodes.Mesh009.geometry}
              material={materials["guns_leather.001"]}
              skeleton={nodes.Mesh009.skeleton}
            />
            <skinnedMesh
              name="Mesh009_1"
              geometry={nodes.Mesh009_1.geometry}
              material={materials["guns_neon.001"]}
              skeleton={nodes.Mesh009_1.skeleton}
            />
            <skinnedMesh
              name="Mesh009_2"
              geometry={nodes.Mesh009_2.geometry}
              material={materials.guns_black}
              skeleton={nodes.Mesh009_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/gltf/m_gunslinger.glb")
